### ISSUE TITLE
chyba pri pokusu o import /faktura-blue.xml

### ISSUE THREAD

**Issue by radar50** [Ch4rlieB/flexibee-reports#1]
pokousim se naimportovat ale dostavam nasledujici chybove hlaseni
860 ERROR XmlImportController:216 - cz.winstrom.service.WSBusinessException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[7,16]
Message: found: DTD, expected START_ELEMENT or END_ELEMENT

Jinak ten layout je fakt hezký :-)

**Comment by Ch4rlieB** [comment]
A stáhnul jste RAW content?
https://raw.githubusercontent.com/Ch4rlieB/flexibee-reports/master/faktura-blue.xml

Můžete mi prosím poslat XML, které se snažíte naimportovat?

**Comment by radar50** [comment]
byl to tenhle soubor

-- 
Mgr. Radim Snajdr
CORAMEXPORT s.r.o.
Josefska 29
571 01 Moravska Trebova
tel. +420-461-311-776

**Comment by Ch4rlieB** [comment]
Můžete mi prosím přesně ten soubor, který se snažíte naimportovat, poslat? Ať to zkouším jak to zkouším, tak mi faktura naimportovat jde.
Na mail info@charlieblog.eu .

Děkuji.
